### ISSUE TITLE
plot_training_samples set to False triggers an error for the generation of dynamic latents

### ISSUE THREAD

**Issue by wissam124** [mirkosavasta/GANetano#2]
Hi,

if ```plot_training_samples``` is set to ```False```, the variable ```noise_length``` is not set and the main training loop (l. 147) will fail because it will try to sample ```dynamic_latents``` with a shape that is only set above (l. 140) when the condition is met.

**Comment by mirkosavasta** [comment]
You are right! I fixed the bug! Thanks for opening this issue!
