### ISSUE TITLE
generate data 

### ISSUE THREAD

**Issue by wmaclaren** [mirkosavasta/GANetano#4]
Hi, Thank you for sharing this code! 
I have a question about how one can use this as a datagenerator. I see that the trainer is the only part that can be used to generate samples. Should one save that using torch.save and then use it to generate several samples of the real data? 

Another question. If I have time-series of size NxT, could one generate synthetic data of that size too? Right now the code generates data of size 16x50. 

Do you have any tips of how to test whether the generated data share similar properties as the real data? 

I really appreciate your help on this.

**Comment by mirkosavasta** [comment]
Hello, 
before you instantiate the trainer, you need to instantiate both the generator and the critic. To generate synthetic data, either save the trained generator or use the saved state dictionaries as I do at line 135 of train.py. The code in this repo generates only univariate time series of length 50. The number 16 you are referring to is the batch size. To generate different time series at once you need to change the code and improve the model.
